INFO:root:called-params configs.yaml
Process Process-1:
Traceback (most recent call last):
  File "/home/lazarosg/miniconda3/envs/ijepa/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/lazarosg/miniconda3/envs/ijepa/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lazarosg/ijepa/main.py", line 57, in process_main
    with open(fname, 'r') as y_file:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'configs.yaml'
